### ISSUE TITLE
Написание тестов для репозиториев

### ISSUE THREAD

**Issue by SamofAnt** [SamofAnt/TravelAgency#10]
Написать тесты для:

- [x] - Репозитория Тур @SamofAnt 
- [x] - Репозитория Турист @Laserkillers 
- [x] - Репозитория Отель @SamofAnt 
- [x] - Репозитория Транспорт @Laserkillers 
- [x] - Репозитория Сотрудник @Laserkillers 
- [x] - Репозитория Страна @Laserkillers 
- [x] - Репозитория Город @SamofAnt 
- [x] - Репозитория Достопримечательность @SamofAnt

**Comment by gtPavelKnnVgt** [comment]
n1.
